# Generated by Django 5.0.2 on 2024-03-02 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_language_alter_file_options_alter_file_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4, unique=True, verbose_name='Til')),
            ],
            options={
                'verbose_name_plural': 'Turi',
                'ordering': ['type'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.type'),
        ),
    ]
